CREATE TABLE IF NOT EXISTS patient_user (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '用户主键',
    user_no VARCHAR(32) NOT NULL COMMENT '用户编号',
    username VARCHAR(64) NOT NULL COMMENT '登录名/账户名',
    password_hash VARCHAR(255) NOT NULL COMMENT '密码哈希',
    real_name VARCHAR(64) NOT NULL COMMENT '真实姓名',
    gender TINYINT NOT NULL DEFAULT 0 COMMENT '性别: 0未知 1男 2女',
    birth_date DATE NULL COMMENT '出生日期',
    phone VARCHAR(20) NOT NULL COMMENT '手机号',
    email VARCHAR(128) NULL COMMENT '邮箱',
    id_card_no VARCHAR(32) NULL COMMENT '身份证号',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态: 1正常 0禁用',
    last_login_at DATETIME NULL COMMENT '最后登录时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除: 0否 1是',
    deleted_at DATETIME NULL COMMENT '删除时间',
    UNIQUE KEY uk_patient_user_user_no (user_no),
    UNIQUE KEY uk_patient_user_username (username),
    UNIQUE KEY uk_patient_user_phone (phone),
    KEY idx_patient_user_status (status),
    KEY idx_patient_user_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户表';

CREATE TABLE IF NOT EXISTS medical_record (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '病历主键',
    record_no VARCHAR(32) NOT NULL COMMENT '病历编号',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    patient_name VARCHAR(64) NOT NULL COMMENT '患者姓名快照',
    age INT NULL COMMENT '年龄',
    chief_complaint VARCHAR(512) NULL COMMENT '主诉',
    present_illness TEXT NULL COMMENT '现病史',
    past_history TEXT NULL COMMENT '既往史',
    allergy_history TEXT NULL COMMENT '过敏史',
    family_history TEXT NULL COMMENT '家族史',
    surgery_history TEXT NULL COMMENT '手术史',
    medication_history TEXT NULL COMMENT '用药史',
    diagnosis_summary TEXT NULL COMMENT '诊断摘要',
    attending_doctor VARCHAR(64) NULL COMMENT '接诊医生',
    record_date DATETIME NOT NULL COMMENT '病历时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除: 0否 1是',
    deleted_at DATETIME NULL COMMENT '删除时间',
    UNIQUE KEY uk_medical_record_record_no (record_no),
    KEY idx_medical_record_user_id (user_id),
    KEY idx_medical_record_record_date (record_date),
    KEY idx_medical_record_user_date (user_id, record_date),
    CONSTRAINT fk_medical_record_user_id FOREIGN KEY (user_id) REFERENCES patient_user (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='病历表';

CREATE TABLE IF NOT EXISTS medical_report (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '报告主键',
    report_no VARCHAR(32) NOT NULL COMMENT '报告编号',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    medical_record_id BIGINT NULL COMMENT '关联病历ID',
    report_type VARCHAR(32) NOT NULL COMMENT '报告类型: blood ct mri pathology ultrasound',
    report_title VARCHAR(128) NOT NULL COMMENT '报告标题',
    hospital_name VARCHAR(128) NULL COMMENT '医院名称',
    department_name VARCHAR(64) NULL COMMENT '科室名称',
    report_date DATETIME NOT NULL COMMENT '报告时间',
    source_type VARCHAR(16) NOT NULL DEFAULT 'UPLOAD' COMMENT '来源类型: UPLOAD OCR MANUAL',
    file_url VARCHAR(255) NULL COMMENT '原始文件地址',
    raw_text LONGTEXT NULL COMMENT '原始文本',
    parsed_json JSON NULL COMMENT '结构化解析结果',
    interpretation_summary TEXT NULL COMMENT '解读摘要',
    risk_level VARCHAR(16) NOT NULL DEFAULT 'LOW' COMMENT '风险等级: LOW MEDIUM HIGH CRITICAL',
    review_status VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '状态: PENDING PARSED REVIEWED FAILED',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除: 0否 1是',
    deleted_at DATETIME NULL COMMENT '删除时间',
    UNIQUE KEY uk_medical_report_report_no (report_no),
    KEY idx_medical_report_user_id (user_id),
    KEY idx_medical_report_record_id (medical_record_id),
    KEY idx_medical_report_report_date (report_date),
    KEY idx_medical_report_status (review_status),
    KEY idx_medical_report_user_date (user_id, report_date),
    CONSTRAINT fk_medical_report_user_id FOREIGN KEY (user_id) REFERENCES patient_user (id),
    CONSTRAINT fk_medical_report_record_id FOREIGN KEY (medical_record_id) REFERENCES medical_record (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='医疗报告表';

CREATE TABLE IF NOT EXISTS chat_session (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '会话主键',
    session_no VARCHAR(32) NOT NULL COMMENT '会话编号',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    medical_record_id BIGINT NULL COMMENT '关联病历ID',
    title VARCHAR(128) NULL COMMENT '会话标题',
    scene_type VARCHAR(32) NOT NULL COMMENT '会话场景: symptom report knowledge mixed',
    current_agent VARCHAR(32) NULL COMMENT '当前处理Agent: router symptom report knowledge',
    session_status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态: ACTIVE CLOSED ARCHIVED',
    summary TEXT NULL COMMENT '会话摘要',
    started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '会话开始时间',
    last_message_at DATETIME NULL COMMENT '最后消息时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除: 0否 1是',
    deleted_at DATETIME NULL COMMENT '删除时间',
    UNIQUE KEY uk_chat_session_session_no (session_no),
    KEY idx_chat_session_user_id (user_id),
    KEY idx_chat_session_record_id (medical_record_id),
    KEY idx_chat_session_status (session_status),
    KEY idx_chat_session_user_last_msg (user_id, last_message_at),
    CONSTRAINT fk_chat_session_user_id FOREIGN KEY (user_id) REFERENCES patient_user (id),
    CONSTRAINT fk_chat_session_record_id FOREIGN KEY (medical_record_id) REFERENCES medical_record (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='聊天会话表';

CREATE TABLE IF NOT EXISTS chat_message (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '消息主键',
    message_no VARCHAR(32) NOT NULL COMMENT '消息编号',
    session_id BIGINT NOT NULL COMMENT '会话ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    report_id BIGINT NULL COMMENT '关联报告ID',
    sender_type VARCHAR(16) NOT NULL COMMENT '发送方: USER AGENT SYSTEM',
    agent_type VARCHAR(32) NULL COMMENT 'Agent类型: router symptom report knowledge',
    message_type VARCHAR(16) NOT NULL DEFAULT 'TEXT' COMMENT '消息类型: TEXT IMAGE FILE REPORT CARD',
    sequence_no INT NOT NULL COMMENT '会话内消息序号',
    content LONGTEXT NOT NULL COMMENT '消息文本内容',
    structured_payload JSON NULL COMMENT '结构化扩展内容',
    citations JSON NULL COMMENT '引用信息',
    tokens_in INT NULL COMMENT '输入token数',
    tokens_out INT NULL COMMENT '输出token数',
    sent_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除: 0否 1是',
    deleted_at DATETIME NULL COMMENT '删除时间',
    UNIQUE KEY uk_chat_message_message_no (message_no),
    UNIQUE KEY uk_chat_message_session_seq (session_id, sequence_no),
    KEY idx_chat_message_user_id (user_id),
    KEY idx_chat_message_report_id (report_id),
    KEY idx_chat_message_session_sent_at (session_id, sent_at),
    CONSTRAINT fk_chat_message_session_id FOREIGN KEY (session_id) REFERENCES chat_session (id),
    CONSTRAINT fk_chat_message_user_id FOREIGN KEY (user_id) REFERENCES patient_user (id),
    CONSTRAINT fk_chat_message_report_id FOREIGN KEY (report_id) REFERENCES medical_report (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='聊天消息表';
